<!-- <div class="header-container">
	<h1><a href=""><img src="/assets/images/logo.png"/></a></h1>
</div> -->
<div class="navbar navbar-default navbar" role="navigation">
	<div class="header-container">
		<div class="container-fluid">
		  <div class="navbar-header">
		    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
		      <span class="sr-only">Toggle navigation</span>
		      <span class="icon-bar"></span>
		      <span class="icon-bar"></span>
		      <span class="icon-bar"></span>
		    </button>
		    <h1><a href="#"><i class="fa fa-bolt"></i></a></h1>
		  </div>
		  <div class="navbar-collapse collapse">
		    <ul class="nav navbar-nav pull-right">
		      <li class="active"><a href="#">How it works</a></li>
		      <li><a href="#">SMS forecast</a></li>
		      <li><a href="#">About us</a></li>
		    </ul>
		  </div><!--/.nav-collapse -->
		</div><!--/.container-fluid -->
	</div>
</div>