<div class="home-container">
	<form action="" method="post" class="weather-form">
		<h3>Ulat Panahon <i class="fa fa-cloud"></i></h3>
		<div class="input-group">
			<input type="hidden" id="remote" value="<?php echo $remote; ?>">
			<input type="text" id="location" class="form-control" placeholder="Taga saan ka ba? You piece of shit!">
			<span class="input-group-btn">
				<button type="submit" class="btn btn-success"><i class="fa fa-search"></i></button>
			</span>
		</div>
	</form>

	<div class="result-container clearfix">
		<div class="weather-map pull-left">
			<p class="title-text"><i class="fa fa-map-marker"></i>&nbsp; Location Map</p><hr>

			<div id="map-canvas">
				<i class="fa fa-map-marker fa-5x"></i>
				<p>Mapa ng lokasyon</p>
			</div>
		</div>

		<div class="forecast-container pull-left">
			<p class="title-text"><i class="fa fa-globe"></i>&nbsp; Current Weather Forecast</p>
			<canvas id="skycons" width="128" height="128ge a"></canvas>
		</div>
	</div>	
</div>

<script type="text/html" id="forecast-template">
	<div class="forecast-template">
		<hr>
		<dl class="dl-horizontal">
			<dt>Location:</dt>
			<dd>[LOCATION]</dd>
			<dt>Summary:</dt>
			<dd>[SUMMARY]</dd>
			<dt>Temperature:</dt>
			<dd>[TEMP]</dd>
			<dt>Humidity:</dt>
			<dd>[HUMIDITY] %</dd>
			<dt>Cloud Cover:</dt>
			<dd>[CLOUD]</dd>
			<dt>Wind:</dt>
			<dd>[WIND] mph</dd>
			<dt>Time:</dt>
			<dd>[TIME]</dd>
			<dt>Latitude:</dt>
			<dd>[LAT]</dd>
			<dt>Longitude:</dt>
			<dd>[LNG]</dd>
		</dl>

		<hr>
		<div class="hourly-forecast">
			<h5><i class="fa fa-compass"></i>&nbsp; Hourly</h5>
			<div class="next-hour clearfix">
				<p class="term pull-left">Next Hour: </p>
				<p class="desc pull-left">[NEXT HOUR]</p>
			</div>

			<div class="hourly-summary clearfix">
				<p class="term term-summary pull-left">Summary: </p>
				<p class="desc desc-summary pull-left">&nbsp; [HOURLY]</p>
			</div>
		</div>

		<hr>
		<div class="daily-forecast">
			<h5><i class="fa fa-tachometer"></i>&nbsp; Daily</h5>
			<div class="next-day clearfix">
				<p class="term pull-left">Next 24 Hour: </p>
				<p class="desc pull-left">[NEXT DAY]</p>
			</div>

			<div class="daily-summary clearfix">
				<p class="term term-summary pull-left">Summary: </p>
				<p class="desc desc-summary  pull-left">&nbsp; [DAILY]</p>
			</div>
		</div>
	</div>
</script>

<script src="https://maps.googleapis.com/maps/api/js?v=3.exp&sensor=false&libraries=places"></script>
<script src="/assets/js/lib/skycons.js"></script>