<div class="home-container">
	<form action="" method="post" class="weather-form">
		<h3>Dahil ang buhay ay Weather Weather lamang</h3>
		<div class="input-group">
			<input type="hidden" id="remote" value="<?php echo $remote; ?>">
			<input type="text" id="location" class="form-control" placeholder="Taga saan ka ba? You piece of shit!">
			<span class="input-group-btn">
				<button type="submit" class="btn btn-info"><i class="fa fa-search"></i></button>
			</span>
		</div>
	</form>

	<div class="result-container clearfix">
		<div class="weather-map pull-left">
			<p class="title-text"><i class="fa fa-map-marker"></i>&nbsp; Location Map</p><hr>

			<div id="map-canvas">
				<i class="fa fa-map-marker fa-5x"></i>
				<p>Mapa ng lokasyon</p>
			</div>
		</div>

		<div class="forecast-container pull-left">
			<p class="title-text"><i class="fa fa-globe"></i>&nbsp; Current Weather Forecast</p>
			<canvas id="skycons" width="64" height="64"></canvas>
		</div>
	</div>	
</div>

<script type="text/html" id="forecast-template">
	<div class="forecast-template">
		<hr>
		<div class="info">
			<ul>
				<li class="info-tab" style="display: block">
					<ul class="info-meta">
						<!-- Currently weather -->
						<li class="first">
							<span class="daydatetime">Mon 08.1.14 <br>[TIME]</span>							
							<div class="temperature">
								<div class="fr">
									<div class="gradus">
										<span class="celsius">° C</span>
										<span class="number">[TEMP]</span>
									</div>
								</div>
							</div>
							<div class="discription">[SUMMARY]</div>
							<div class="windchill">[LOCATION]</div>
							<div class="other">
								<span class="humidity">
									<img src="/assets/images/humidity.png" width="32" height="32" title="Humidity" class="icon">
									<span class="point">[HUMIDITY]</span>%
								</span>								
								<span class="cloud">
									<img src="/assets/images/cloudy.png" width="32" height="32" title="Cloud cover" class="icon">
									<span class="point">[CLOUD]</span>%
								</span>
								<span class="wind">
									<img src="/assets/images/windImgE.png" width="32" height="32" title="East" class="icon"> 
									<span class="point">[WIND]</span>							
								</span>
								<span class="rainpos">
									<img src="/assets/images/posrain.png" width="32" height="32" title="Rain possibility" class="icon">
									<span class="point">[PRESSURE]</span>
								</span>

							</div>
						</li>
						<!-- End Currently weather -->
					</ul>
				</li>
			</ul>			
		</div>

		<hr>
		<div class="hourly-forecast">
			<h5><i class="fa fa-compass"></i>&nbsp; Hourly</h5>
			<dl class="dl-horizontal">
				<dt>Next Hour:</dt>
				<dd>[NEXT HOUR]</dd>			
				<dt>Summary: </dt>
				<dd>[HOURLY]</dd>
			</dl>
		</div>

		<hr>
		<div class="daily-forecast">
			<h5><i class="fa fa-tachometer"></i>&nbsp; Daily</h5>
			<dl class="dl-horizontal">
				<dt>Next 24 Hours:</dt>
				<dd>[NEXT DAY]</dd>
				<dt>Summary: </dt>
				<dd>[DAILY]</dd>
			</dl>
		</div>
	</div>
</script>

<script src="https://maps.googleapis.com/maps/api/js?v=3.exp&sensor=false&libraries=places"></script>
<script src="/assets/js/lib/skycons.js"></script>